### ISSUE TITLE
Saving the draw by finger graphics.

### ISSUE THREAD

**Issue by sawepeter** [dakshbhatt21/a-computer-engineer#1]
I tried implementing the guideline given here: https://acomputerengineer.wordpress.com/2015/01/13/how-to-draw-canvas-on-imageview-and-save-canvas-as-bitmap-and-store-in-sdcard-in-android/
but it fails to work.How can i be in a position to save the specific drawn graphics like the way we saved the above "canvas.drawText("Sample Text", 100, 100, pText);".Any help will be highly appreciated

**Comment by daksh-huma** [comment]
Hello!

Sorry for the late reply. I actually did not get your question correctly. So the clarification would be great.

You can save anything that drawn on canvas to bitmap. If that was your question.
Or you can draw anything on canvas like shape, image, text, line, polygons, etc. Here we draw text on the canvas but you can draw anything.

I hope this answers your questions.

**Comment by sawepeter** [comment]
Thanks a lot. I was able to solve the problem. I initially wanted to come with something whereby I could be able to draw anything on the canvas. Thanks a lot for finding time to respond to me

**Comment by dakshbhatt21** [comment]
Great!
